# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sejal-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://sejal.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1076c25de8b74874997cadd0c633dd12 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e962decc93224717be478d089f3847cc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sejal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1076c25de8b74874997cadd0c633dd12 }}/attdsejalfrontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sejal-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1be4a26ca47e4ed39b3a28617fd0eb83 }}
        images: 'sejal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1076c25de8b74874997cadd0c633dd12 }}/attdsejalfrontend:${{ github.sha }}'