name: Flask Backend - Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://sejal.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_211b51812f594d75bec1b978c201d516 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9030388df38449c0b086862e9dba6df7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sejal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_211b51812f594d75bec1b978c201d516 }}/attdsejalbackend:${{ github.sha }}
        context: ./attd-sejal-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sejal-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc417ccc628345bb8f55b742962092ed }}
        images: 'sejal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_211b51812f594d75bec1b978c201d516 }}/attdsejalbackend:${{ github.sha }}'
